import { Ticket } from "../../src/app/models/ticket";

export const  jergi_ticket:Ticket = {
    "winner1":"France",
    "winner2": "Nemecko",
    "topStriker":"Mbappe",
    "matches":{
        "Germ:Scot":{"homeScore":2,"awayScore":0},"Hung:Swit":{"homeScore":2,"awayScore":1},"Spai:Croa":{"homeScore":2,"awayScore":1},"Ital:Alba":{"homeScore":2,"awayScore":0},"Slov:Denm":{"homeScore":1,"awayScore":1},"Serb:Engl":{"homeScore":1,"awayScore":3},"Pola:Neth":{"homeScore":1,"awayScore":3},"Aust:Fran":{"homeScore":0,"awayScore":2},"Roma:Ukra":{"homeScore":0,"awayScore":2},"Belg:Slov":{"homeScore":2,"awayScore":0},"Turk:Geor":{"homeScore":1,"awayScore":1},"Port:Czec":{"homeScore":2,"awayScore":1},"Germ:Hung":{"homeScore":2,"awayScore":1},"Scot:Swit":{"homeScore":1,"awayScore":1},"Croa:Alba":{"homeScore":2,"awayScore":0},"Spai:Ital":{"homeScore":2,"awayScore":0},"Slov:Serb":{"homeScore":1,"awayScore":2},"Denm:Engl":{"homeScore":0,"awayScore":2},"Pola:Aust":{"homeScore":1,"awayScore":1},"Neth:Fran":{"homeScore":2,"awayScore":2},"Slov:Ukra":{"homeScore":1,"awayScore":0},"Belg:Roma":{"homeScore":3,"awayScore":0},"Geor:Czec":{"homeScore":0,"awayScore":2},"Turk:Port":{"homeScore":0,"awayScore":3},"Swit:Germ":{"homeScore":0,"awayScore":2},"Scot:Hung":{"homeScore":0,"awayScore":2},"Alba:Spai":{"homeScore":0,"awayScore":3},"Croa:Ital":{"homeScore":2,"awayScore":1},"Engl:Slov":{"homeScore":3,"awayScore":0},"Denm:Serb":{"homeScore":1,"awayScore":2},"Neth:Aust":{"homeScore":2,"awayScore":1},"Fran:Pola":{"homeScore":3,"awayScore":1},"Slov:Roma":{"homeScore":2,"awayScore":1},"Ukra:Belg":{"homeScore":0,"awayScore":2},"Geor:Port":{"homeScore":0,"awayScore":3},"Czec:Turk":{"homeScore":2,"awayScore":0},"Swit:Ital":{"homeScore":2,"awayScore":1},"Germ:Denm":{"homeScore":2,"awayScore":0},"Slov:Engl":{"homeScore":0,"awayScore":2},"Spai:Geor":{"homeScore":2,"awayScore":0},"Fran:Belg":{"homeScore":2,"awayScore":1},"Port:Slov":{"homeScore":2,"awayScore":0},"Roma:Neth":{"homeScore":0,"awayScore":2},"Aust:Turk":{"homeScore":2,"awayScore":0}
    ,"Spai:Germ":{"homeScore":1,"awayScore":1},"Port:Fran":{"homeScore":1,"awayScore":1},"Engl:Swit":{"homeScore":0,"awayScore":1},"Neth:Turk":{"homeScore":2,"awayScore":0}
    }
}